[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
impaired = { path = "../impaired" }

getch = "0.3.1"
itertools = "0.10.3"

[[example]]
name = "simple_cli"
path = "simple_cli.rs"
